In [1]:
import numpy as np
import pandas as pd

In [3]:
bios=pd.read_excel("../data/olympics-data.xlsx")

In [5]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [6]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [7]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [10]:
bios.loc[[0,1], ["athlete_id", "name"]]

   athlete_id                   name
0           1  Jean-François Blanchy
1           2         Arnaud Boetsch

In [11]:
bios.isnull()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,False,False,False,False,False,False,False,True,True,False
1,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...
145495,False,False,False,False,False,False,False,False,False,True
145496,False,False,False,False,False,False,False,False,False,True
145497,False,False,False,False,False,False,False,False,False,True
145498,False,False,False,False,False,False,False,False,True,False
145499,False,False,False,False,False,False,False,True,True,False

In [12]:
bios.loc[bios["height_cm"]>200, ["name", "height_cm"]]

                      name  height_cm
1080        Bozhil Lozanov      208.0
1673      Alexis Rubalcaba      204.0
2647         Milan Šrejber      203.0
2827    Nik'oloz Deriugini      206.0
2832         Elşad Qadaşev      205.0
...                    ...        ...
143784  Daniel Miklasevich      203.0
143833  Garrett Muagututia      205.0
143834         Kyle Ensing      201.0
143835         Mitch Stahl      203.0
143919   Emerson Rodríguez      204.0

[1219 rows x 2 columns]

In [18]:
bios.loc[bios["born_country"]=="USA", ["name", "born_region", "born_country"]]

                     name  born_region born_country
54          Monique Javer   California          USA
960      Xóchitl Escobedo   California          USA
961     Angélica Gavaldón   California          USA
1231       Bert Schneider         Ohio          USA
1345           Laura Berg   California          USA
...                   ...          ...          ...
145445     Kristen Santos  Connecticut          USA
145446   Corinne Stoddard   Washington          USA
145454      Anna Hoffmann    Wisconsin          USA
145457     Alix Wilkinson   California          USA
145468  Justin Abdelkader     Michigan          USA

[9641 rows x 3 columns]

In [16]:
bios.loc[bios["born_date"].notnull(), ["name", "born_date", "born_region"]]

                         name   born_date           born_region
0       Jean-François Blanchy  1886-12-12               Gironde
1              Arnaud Boetsch  1969-04-01              Yvelines
2                Jean Borotra  1898-08-13  Pyrénées-Atlantiques
3             Jacques Brugnon  1895-05-11                 Paris
4                Albert Canet  1878-04-17               England
...                       ...         ...                   ...
145495      Polina Luchnikova  2002-01-30            Sverdlovsk
145496    Valeriya Merkusheva  1999-09-20                Moskva
145497        Yuliya Smirnova  1998-05-08           Arkhangelsk
145498         André Foussard  1899-05-19           Deux-Sèvres
145499          Bill Phillips  1913-07-15       New South Wales

[143693 rows x 3 columns]